#!/bin/bash

#-----------------------|DOCUMENTATION|-----------------------#
# @descr: Script to test the Makefile
# @fonts: 	
# @example:
#       bash Makefile.test plan
#    OR
#       bash Makefile.test compile
#-------------------------------------------------------------#

# @descr: Main function of the script, it runs automatically on the script call.
# @param: 
#    $@ | array: (*)
function MakefileTest {
    local template="coreos-stable-vagrant.json";
    local variables="vars-global.json vars-coreos.json vars-vagrant.json vars-custom.json";
    local packer_only="virtualbox-iso";

    local coreos_release="stable";
    local coreos_version="1576.5.0";

    local ARGUMENTS="TEMPLATE=${template} VARIABLES='${variables}' PACKER_ONLY=${packer_only} COREOS_RELEASE=${coreos_release} COREOS_VERSION=${coreos_version}";

    case "$@" in
        plan) {
            make plan $ARGUMENTS;

        };;
        compile) {
            make plan compile $ARGUMENTS;

        };;
        validate) {
            make plan validate $ARGUMENTS;

        };;
        build) {
            make plan build $ARGUMENTS;

        };;
        build-force) {
            make build-force $ARGUMENTS;

        };;
        install-box) {
            make plan install-box $ARGUMENTS;

        };;
        publish-box) {
            make plan publish-box $ARGUMENTS;

        };;
        uninstall-box) {
            make plan uninstall-box $ARGUMENTS;

        };;
        clean) {
            make plan clean $ARGUMENTS;

        };;
        *) {
            echo "WARNING: The test type has not been passed or is incorrect.";
        };;
    esac
}

# @descr: Call of execution of the script's main function.
MakefileTest "$@" 2>&1 | tee Makefile.test.log;

# @descr: Finishing the script!!! :P
exit 0;